### PR TITLE
sync some changes from upstream

### PR DESCRIPTION
**Pull request by waldyrious**
See https://github.com/hacktoon/ink2canvas/blob/master/ink2canvas/svg/Path.py

### CODE REVIEW

**Comment by christofferholmstedt** [comment]
Hi @waldyrious 
Inkscape project still manage code on Launchpad and not on Github. Do you have an account there?

**Comment by waldyrious** [comment]
I do have an account on Launchpad, but I've never sent code contributions there (I mostly use it to keep track of bug reports and occasionally comment on them).

In any case, I did check the README beforehand, and thought contributing through github was OK, since I read in the "[Contributing](https://github.com/inkscape/inkscape#contributing)" section:

> You may also fork / pull request and use the issue tracker here as a simple way to submit changes to the project.

Did I misinterpret the cases where that option applies?

**Comment by christofferholmstedt** [comment]
No, you did not misinterpret that. Every bit of help for the project is appreciated.

The process is still that someone needs to open an issue on Launchpad and submit the patch there, either you do it or I do it for you.

**Comment by waldyrious** [comment]
If it wouldn't be much hassle, I'd appreciate if you did. I never submitted patches Launchpad before, and I assume you probably have the setup in place to do that quickly. If that's not the case, I can do it, but I'd need some pointers :)

**Comment by christofferholmstedt** [comment]
Tracked in Launchpad at https://bugs.launchpad.net/inkscape/+bug/1609920

**Comment by waldyrious** [comment]
Thanks, I'll watch that bug for updates.

**Comment by waldyrious** [comment]
I'm sorry for commenting here, but issues were disabled, apparently :( in fact, I was tracking issue #21 (Migrate Launchpad to GitHub) with much interest, and having it disappear into thin air leaves me both concerned about the decisions that went into disabling issues in this repo (which weren't documented anywhere as far as I could tell -- a good place would be CONTRIBUTING.md), and sad that the discussion in that thread (and others) won't be documented for future reference.

Pinging those who Github tells me were involved in #21, based on the notification I got of it having undergone changes (which I can't see what they were since the link now 404's): @doctormo, @shakaran, @fulldecent. Any clarification would be appreciated.

**Comment by shakaran** [comment]
@waldyrious Yes, I am very surprised too for the "take down" of remove all the issues and move again all to launchpad. It is clear that github was doing a good job showing the commits, and having the issues, even getting contributions useful for inkscape but Martin Owens just decide in a dictatorial way remove all the issues, close it and stay again in launchpad. I disagree a lot this change, it is not the expected in a open source community and I am for sure that github will help more tracking issues and getting contributions than the actual launchpad tracker where I have bugs reported with more than 3 years without resolve. Thanks for nothing.

**Comment by bryceharrington** [comment]
shakaran, don't be irate at Martin - I was the one that directed to have the github issues closed after he asked what to do, so please direct ire my way.

It is a fact that the Inkscape project is considering a transition to github or gitlab.  However, the consensus we have built is for transitioning to github or gitlab only for source code and CI; there is not a strong consensus for migrating the issue tracking here.  I know that there are many people accustomed to github bug tracking, and that prefer it over launchpad (for quite legitimate reasons), but understand that by this point we've built up a *large* base of bug reviewers and bug fixers who are knowledgeable and comfortable with launchpad, that are reticent to move (also for quite legitimate reasons).  Since the principle value we all gain from a bug tracking system is to get our bug reports resolved, it makes the most sense to heavily weigh the preferences of people who are resolving the bug reports, and make doubly sure it is satisfying their needs, even if it might not be ideal for everyone filing bugs.

Keep also in mind that by this point we've accumulated thousands of bug reports, and transitioning to a new system also presents a bit of a logistical challenge, all by itself.  That's not a reason not to change, but it is a reason to be extra deliberate in our choice.  Your remark about bugs being open >3 years is unfortunately a fact, and it bothers me too; many of the bugs are non-trivial, and the number of volunteers we have working on bugs compared with the number of users filing bugs is quite low, so sadly many bugs go for a long, long time without being looked at.  We really value the help of people putting in time looking at them, and especially those folks working to get them resolved.

My guess is that the github issues system was either enabled by default when the project was set up here, or else it was turned on for experimental purposes.  Whatever the case, fact is no one that can resolve bugs will be looking here, so having the tracker open is a disservice to users like you who want to help Inkscape by reporting problems you're finding, only to later find no one is going to act on it.  When I heard people were filing bugs here I requested it be turned off ASAP so others don't fall into the trap too.

It's entirely possible we might consider using github issues in the future (although from what I've gathered I think it's extremely unlikely), but there hasn't been a decision to use it, so having it turned on was a bit of an accident.  I apologize that the decision process was not done transparently enough, and hope my above dissertation explains the thinking that was going on.

**Comment by waldyrious** [comment]
@bryceharrington I appreciate the detailed and level-headed write-up. I am just concerned that you guys are worrying about the *current* universe of bug-fixers and patch-senders who are used to launchpad, and ignoring the much larger universe of *potential* bug-fixers that would get involved if development used a platform that is more friendly to beginners (which I offer that either github or gitlab are, compared to launchpad).

This very issue is a case in point: I've been an Inkscape user and a FOSS contributor for several years, but even when I went out of the way to provide a patch to a project that clearly wasn't being actively maintained in the platform I used (github), what I faced was logistical hoops which, were I to attempt to overcome, would whittle away energy that otherwise would go to addressing the task itself. Consider how many more people don't even try after seeing the trajectory of PRs like this, or the [pulse of the project](https://github.com/inkscape/inkscape/pulse), or the sparse contents of the master branch, particularly [ALL-CODE-IS-IN-THE-BZR-ORIGINAL-BRANCH.md](https://github.com/inkscape/inkscape/blob/master/ALL-CODE-IS-IN-THE-BZR-ORIGINAL-BRANCH.md).

My point is that you must consider the fact that github participation is lower than launchpad's not only because the project grew on launchpad where established contributors have built a comfortable (as in familiar) workflow over the years, but also because on github the whole setup seems to discourage people to even *start* getting involved, getting their feet wet with small stuff like this one, let alone investing a whole lot more of their time addressing more complex issues, which for all they can see could well end up being wasted time (even if just due to bitrot due to slow progress on the patch's review / integration).

As I've told Martin privately, I will keep an eye on any news regarding the transition you're discussing (either github or gitlab would be fine IMO), and hoping that these news don't take too much longer to arrive :)

**Comment by hadim** [comment]
Just my two cents here to insist about what @waldyrious said because I think it's critical for Inkscape future.

Even if your current bug fixers are used to launchpad right now I am pretty sure new bug fixers are unlikely to come due to the launchpad software itself which make contributions/reviewing hard and painfull.

Ok github is closed source and that's a big downside but if you have used the tool in the past you know it's worth it. 

Maybe I am wrong but I would bet for a big increase in contributions/contributors if you move the code/issues/PR to github.

So it might be a smart move for the current bug fixers to move to github so they will potentially be able to interact with a much bigger contributors pool. 

Having said that I really hope Inkscape future will be plenty of wonderfull release and will increase its already pretty big userbase. Because the software and its community deserve it !

**Comment by fulldecent** [comment]
Let's just have one battle at a time. If we can get contributors using the Inkscape codebase (without issues) on GitHub, this will be a huge improvement. This is how Apple does it with the Swift project, see https://github.com/apple/swift

Of course, GitHub's ease of use and its many members will start attracting pull requests from people that hadn't contributed before, and wouldn't have if they needed to use Launchpad.

When many more contributors are coming in that way then obviously that would be a good time to consider migrating the issues.

---

FYI: I am turning tasks and wiki back on now. Will turn tasks off after I retrieve the notes from issues #21. I am keeping my notes in Wiki now and I'll leave that enabled. Please don't turn it off. Specifically, that is where I keep my instructions for syncing GitHub to upstream bzr. Just did a pull now to get all the new great stuff in there!

**Comment by fulldecent** [comment]
I have disabled Issues again. The previous work plan from issue #21 is now at https://github.com/inkscape/inkscape/wiki/Migrate-Launchpad-to-GitHub-%5BDRAFT%5D

I have marked progress there as has been completed.

**Comment by waldyrious** [comment]
@fulldecent thanks for moving forward with this! I know such a transition an be *a lot* of work (I did it for a small svn project from sourceforge a while ago), so let us know if there's anything specific (small or divisible tasks would be ideal) we can do to help out :)

**Comment by fulldecent** [comment]
@waldyrious Thank you for your support. Right now here are remaining tasks:

 - [ ] Create the best possible README.md for when we switch over to GitHub for hosting code 
    - Can go here https://github.com/inkscape/inkscape/blob/master/README-FOR-AFTER-SWITCHOVER/README.md
    - Can use pull requests here to update this file
    - It should reflect our cutover plan (allow pull requests on GitHub but note that issues should go through LaunchPad)
    - It should be an awesome page, and very consistent with the https://inkscape.org/ homepage
 - [ ] Open a discussion in the https://inkscape.org/en/community/mailing-lists/#inkscape-devel mailing list to evaluate the cutover plan at https://github.com/inkscape/inkscape/wiki/Migrate-Launchpad-to-GitHub-%5BDRAFT%5D and garner support for cutover and set a cutover date

**Comment by waldyrious** [comment]
Ok, I sent #29 for a start :)

**Comment by hadim** [comment]
I have setup a small Dockerfile to build Inkscape under Linux. That's a first step before using an online CI tool such as CircleCI.

https://github.com/hadim/docker-inkscape

For now it only does the build but in the future we could imagine generating .deb or .rpm packages with it.

Hope it helps moving forward.

**Comment by fulldecent** [comment]
@hadim Inkscape already has CI set up with Jenkins. Moving to the more popular stuff on GitHub is something we would want to do *after* convincing everyone of how easy and painfree the switch to GitHub is :-)

**Comment by hadim** [comment]
Hey guys,

Any news about moving inkscape to git ?

**Comment by fulldecent** [comment]
Per https://github.com/inkscape/inkscape/pull/20#issuecomment-253333843

Please open a discussion on Inkscape-devel and cross link there to here. This is the next step to officially evaluate our migration plan.

**Comment by luzpaz** [comment]
@hadim FYI inkscape is using gitlab now https://gitlab.com/inkscape/inkscape
Perhaps you can submit the PR there ?

**Comment by christofferholmstedt** [comment]
@luzpaz and @hadim Code has been moved to GitLab but not issue tracking. It is being discussed. Issue tracking is still on Launchpad.

**Pull request closed without merging**
